### ISSUE TITLE
Support for vue-router

### ISSUE THREAD

**Issue by JanCVanB** [gvaldambrini/storybook-router#11]
Now that Storybook supports Vue, does this project have any interest in supporting vue-router?

Link: https://github.com/vuejs/vue-router

Related: https://github.com/storybooks/storybook/issues/1657

**Comment by ndelangen** [comment]
Would you be interested in helping achieve support? 🙇

**Comment by JanCVanB** [comment]
@ndelangen Sure! I'm very busy this month, but I'd love to help soon.

**Comment by gvaldambrini** [comment]
@JanCVanB give me some days to explore how doable / complicated is. As I'm new to Vue (and so, vue-router), any suggestion would be appreciated.

**Comment by JanCVanB** [comment]
@gvaldambrini Thanks, let me know what you find+think!

**Comment by gvaldambrini** [comment]
I created an experimental branch called vue with the support to vue-router. For anyone interested just install the package from the github url:
```npm install git://github.com/gvaldambrini/storybook-router.git#vue```
In tried to maintain the API as similar as possible to the React one, so the decorator accepts two arguments: the links object and a config object (the router props). I'm still in an early stage so any feedback (about the code of the decorator itself or about the expected behaviour) would be really appreciated.

**Comment by ndelangen** [comment]
@gvaldambrini ❤️

**Comment by gvaldambrini** [comment]
The vue support has been released. Please open a dedicated issue for any problem.

**Comment by JanCVanB** [comment]
Awesome, @gvaldambrini, thanks! :D I'm excited to try it in my router-heavy project.

**Comment by kazupon** [comment]
awesome! ❤️
